version: "3"
services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./web/app:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file: .env
    environment:
      - DEBUG=TRUE

  redis:
    image: "redis:alpine"

  celery:
    build: ./web
    command: celery -A app worker -l info
    volumes:
      - ./web/app:/app
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DEBUG=TRUE

  celery-beat:
    build: ./web
    command: celery -A app beat -l info
    volumes:
      - ./web/app:/app
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DEBUG=TRUE

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
# TIP: docker-compsoe automatically adds folder name as prefix
# to volumes' names. It could cause problems if you change folder name
# to control this you can run docker-compose with -p flag
# example: docker-compose -p "your_prefix" up
