version: "3"
services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./web/app:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file: .env
    environment:
      - DEBUG=TRUE

  redis:
    image: "redis:alpine"

  celery:
    build: ./web
    command: celery -A app worker -l info
    volumes:
      - ./web/app:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: ./web
    command: celery -A app beat -l info
    volumes:
      - ./web/app:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
